<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select State Andaman and NicobarAndh_a90a90</name>
   <tag></tag>
   <elementGuidId>4901cc2b-9d6e-4ad4-9170-e66b4f284144</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='StateId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#StateId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#StateId</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8dc6f2b6-0c36-450e-bcda-8b1a9f2b13ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>state_id</value>
      <webElementGuid>d6d7c339-2c9b-4871-b98c-0ba416381ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>StateId</value>
      <webElementGuid>bf4d99df-5be2-4595-9787-061919e3209a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control select-arrow-cust widget_input</value>
      <webElementGuid>c6056cf7-9797-425c-8259-526a097b839f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>GetChildByMachineKey(this.value,'CityId');</value>
      <webElementGuid>6f70df58-bec1-45cf-98df-22414ce5abab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Select State *</value>
      <webElementGuid>68f54d32-2774-402c-bd1f-b2267570cb5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-none-selected-text</name>
      <type>Main</type>
      <value>Select State</value>
      <webElementGuid>ff322fb9-ff3a-4507-81d0-646204f7db94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select State *Andaman and NicobarAndhra PradeshArunachal PradeshAssamBiharChandigarhChhattisgarhDadra And Nagar HaveliDaman And DiuDelhiGoaGujaratHaryanaHimachal PradeshJammu and KashmirJharkhandKarnatakaKeralaLadakhLakshadweepMadhya PradeshMaharashtraManipurMeghalayaMizoramNagalandOdishaPuducherryPunjabRajasthanSikkimTamil NaduTelanganaTripuraUttar PradeshUttarakhandWest Bengal</value>
      <webElementGuid>d1441104-1c58-4367-8784-c39193cd741c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;StateId&quot;)</value>
      <webElementGuid>a58f40ef-bebb-4cc5-9e2b-8ed81cb2236e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='StateId']</value>
      <webElementGuid>056311ea-7505-4788-9ba2-6c96c8934955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerForm']/div[2]/div[4]/select</value>
      <webElementGuid>aa2a5505-18fa-466a-9b7f-88a1b1fb5c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/preceding::select[5]</value>
      <webElementGuid>f0e1dc7f-5899-4247-bd59-f2fd380e2aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I agree to receive information by signing up on Kalasalingam Academy of Research and Education *'])[1]/preceding::select[5]</value>
      <webElementGuid>e4c63642-33e0-4e7d-b278-9a7f0b78bc99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>5abb2777-3e7a-43a9-825a-00165c99ec64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'state_id' and @id = 'StateId' and (text() = 'Select State *Andaman and NicobarAndhra PradeshArunachal PradeshAssamBiharChandigarhChhattisgarhDadra And Nagar HaveliDaman And DiuDelhiGoaGujaratHaryanaHimachal PradeshJammu and KashmirJharkhandKarnatakaKeralaLadakhLakshadweepMadhya PradeshMaharashtraManipurMeghalayaMizoramNagalandOdishaPuducherryPunjabRajasthanSikkimTamil NaduTelanganaTripuraUttar PradeshUttarakhandWest Bengal' or . = 'Select State *Andaman and NicobarAndhra PradeshArunachal PradeshAssamBiharChandigarhChhattisgarhDadra And Nagar HaveliDaman And DiuDelhiGoaGujaratHaryanaHimachal PradeshJammu and KashmirJharkhandKarnatakaKeralaLadakhLakshadweepMadhya PradeshMaharashtraManipurMeghalayaMizoramNagalandOdishaPuducherryPunjabRajasthanSikkimTamil NaduTelanganaTripuraUttar PradeshUttarakhandWest Bengal')]</value>
      <webElementGuid>ef44bc3b-dcc8-42d3-949d-6aeb8b1716ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
