<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Program B.AB.B.AB.C.AB.ComB.Sc</name>
   <tag></tag>
   <elementGuidId>8e76ba12-19e9-48e5-8a6a-c373f06e5651</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='CourseId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CourseId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#CourseId</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b9652fc6-4423-4e7b-b5ff-1a3b1c21e853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>course_id</value>
      <webElementGuid>2df96a8c-f411-451c-a605-ff1af68a7286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CourseId</value>
      <webElementGuid>4b0e88c3-74dd-493f-b726-6fc906287677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control select-arrow-cust widget_input</value>
      <webElementGuid>02b37cdb-36a6-47bd-80ae-ae8d4d048d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>GetChildByMachineKey(this.value,'SpecializationId');</value>
      <webElementGuid>97fe88f3-11c3-4e05-b6f4-46b2aa0a78a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Select Program *</value>
      <webElementGuid>bd52c378-250b-4a7a-9828-b40836e32866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-none-selected-text</name>
      <type>Main</type>
      <value>Select Program</value>
      <webElementGuid>cbbe71e2-feb9-4672-a410-4deb24e1a643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Program *B.AB.B.AB.C.AB.ComB.Sc.</value>
      <webElementGuid>eda9b2db-5c08-44dd-af69-dd0f5584f23b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CourseId&quot;)</value>
      <webElementGuid>66a44818-e8fd-40f3-803c-1ca087fe31bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='CourseId']</value>
      <webElementGuid>488eddb4-e07b-4e0f-9dff-3dd75807e73c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerForm']/div[2]/div[8]/select</value>
      <webElementGuid>2192c2e1-0405-42b7-9d8a-46c0241617ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/preceding::select[2]</value>
      <webElementGuid>f13f793f-a50b-4130-b7a5-a685d1b7b429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I agree to receive information by signing up on Kalasalingam Academy of Research and Education *'])[1]/preceding::select[2]</value>
      <webElementGuid>b5777fa2-1908-4a9b-a275-f422ab2a69a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/select</value>
      <webElementGuid>8b10d81b-17d0-4ded-9a98-6395ef42ca37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'course_id' and @id = 'CourseId' and (text() = 'Select Program *B.AB.B.AB.C.AB.ComB.Sc.' or . = 'Select Program *B.AB.B.AB.C.AB.ComB.Sc.')]</value>
      <webElementGuid>8c72a824-ad41-4558-9347-642fdbd2e9d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
