<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select School School of EngineeringS_c5e75e</name>
   <tag></tag>
   <elementGuidId>579a224e-6f75-4d16-bfb0-7c13f0435b56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='UniversityId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#UniversityId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#UniversityId</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6d6b69ed-1734-490d-a860-08443264c032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>university_id</value>
      <webElementGuid>73ff9611-5cfe-4d9b-a6b2-2d00f3abce78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UniversityId</value>
      <webElementGuid>a79d2032-7b25-466a-94b1-ca484f1cdb6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control select-arrow-cust widget_input</value>
      <webElementGuid>b16f582b-b46b-4026-9091-fa6e1417992f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>GetChildByMachineKey(this.value,'CourseId');</value>
      <webElementGuid>a7537541-a196-4168-9749-12bcfefda58e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Select School *</value>
      <webElementGuid>842c8254-e4ef-4803-9174-9f59d816dea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-none-selected-text</name>
      <type>Main</type>
      <value>Select School</value>
      <webElementGuid>33f25a4b-0515-4bb3-8698-8667bdaa5f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select School *School of EngineeringSchool of ArchitectureSchool of LawSchool of Agriculture &amp; HoricultureSchool of Allied Health SciencesUG Arts and SciencePost Graduate degreeSpeech &amp; Hearing Impaired Programme (SHIP)Online Learning (OL)Online Distance Learning (ODL)Ph.D. Programme</value>
      <webElementGuid>f2372f9d-e37e-4dd8-8457-0ab7f3f4f485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UniversityId&quot;)</value>
      <webElementGuid>f7e219db-a240-425e-95a0-df8560e51bec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='UniversityId']</value>
      <webElementGuid>f403382d-3d87-431d-8511-cd0aafa629f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerForm']/div[2]/div[7]/select</value>
      <webElementGuid>bb2bc96c-4eaf-4a43-90dd-11ca0d7b4b53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/preceding::select[3]</value>
      <webElementGuid>5a215c82-301a-45fc-886b-003d40a95c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I agree to receive information by signing up on Kalasalingam Academy of Research and Education *'])[1]/preceding::select[3]</value>
      <webElementGuid>dc425ada-74ad-41ad-9c3b-dca2df0a4de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/select</value>
      <webElementGuid>de136bb9-c11b-45fa-8749-7975d9497452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'university_id' and @id = 'UniversityId' and (text() = 'Select School *School of EngineeringSchool of ArchitectureSchool of LawSchool of Agriculture &amp; HoricultureSchool of Allied Health SciencesUG Arts and SciencePost Graduate degreeSpeech &amp; Hearing Impaired Programme (SHIP)Online Learning (OL)Online Distance Learning (ODL)Ph.D. Programme' or . = 'Select School *School of EngineeringSchool of ArchitectureSchool of LawSchool of Agriculture &amp; HoricultureSchool of Allied Health SciencesUG Arts and SciencePost Graduate degreeSpeech &amp; Hearing Impaired Programme (SHIP)Online Learning (OL)Online Distance Learning (ODL)Ph.D. Programme')]</value>
      <webElementGuid>d055093b-6e62-45cc-bdc3-e15865efd420</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
