<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Course Mathematics with Compu_3c2021</name>
   <tag></tag>
   <elementGuidId>f9abc168-5326-40c7-a8b6-b2c25ca9109f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='SpecializationId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SpecializationId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#SpecializationId</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2b68f655-abc7-4ed6-b89c-53bf294e6c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>specialization_id</value>
      <webElementGuid>ae7da36c-7cd8-4b7e-97d6-754e2d39512e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SpecializationId</value>
      <webElementGuid>31f43fc6-7919-462a-8674-1a323c3458fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Select Course *</value>
      <webElementGuid>2a19635f-ea35-42a0-b4b9-34a88aaa779c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control select-arrow-cust widget_input</value>
      <webElementGuid>c7135060-c73b-4b0f-b4cd-58fdb5ae8117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-none-selected-text</name>
      <type>Main</type>
      <value>Select Course</value>
      <webElementGuid>74c5c19c-2ae5-4568-bf8b-c370fc99aa4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Course *Mathematics with Computer ApplicationsPhysics with Computer ApplicationsChemistryComputer ScienceInformation TechnologyForensic ScienceVisual CommunicationCatering Science and Hotel ManagementFire &amp; SafetyFashion Design</value>
      <webElementGuid>6d73fc60-fc38-4817-8d3b-61e9ea8d4c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SpecializationId&quot;)</value>
      <webElementGuid>75bd6160-4626-44a4-87a3-498cee124d64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='SpecializationId']</value>
      <webElementGuid>6fee698a-ed58-428e-bd1e-81ead2282d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerForm']/div[2]/div[9]/select</value>
      <webElementGuid>73783b0e-2479-4f7c-becc-f768b53ddab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/preceding::select[1]</value>
      <webElementGuid>9f7b6e88-c538-4183-ac1b-4822357bcb4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I agree to receive information by signing up on Kalasalingam Academy of Research and Education *'])[1]/preceding::select[1]</value>
      <webElementGuid>db0665ec-4d6c-42fd-acff-18a9ad1e75c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/select</value>
      <webElementGuid>91141a1e-32ac-47d1-90df-7fe485ea51ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'specialization_id' and @id = 'SpecializationId' and (text() = 'Select Course *Mathematics with Computer ApplicationsPhysics with Computer ApplicationsChemistryComputer ScienceInformation TechnologyForensic ScienceVisual CommunicationCatering Science and Hotel ManagementFire &amp; SafetyFashion Design' or . = 'Select Course *Mathematics with Computer ApplicationsPhysics with Computer ApplicationsChemistryComputer ScienceInformation TechnologyForensic ScienceVisual CommunicationCatering Science and Hotel ManagementFire &amp; SafetyFashion Design')]</value>
      <webElementGuid>e6220080-e11f-4aac-8fd1-79ff1457736b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
