<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select City AgasteeswaramAlangudiAla_705298</name>
   <tag></tag>
   <elementGuidId>0fa2965c-0bf7-4287-80f0-be25809aab3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='CityId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CityId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#CityId</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cdf0a613-c0e6-4e22-a8d3-6516dc1e004b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city_id</value>
      <webElementGuid>5a6e7516-4868-4d3c-8f46-ed73167de396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CityId</value>
      <webElementGuid>678cb12c-0df7-4fb8-b9b5-32105874bd69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control select-arrow-cust widget_input</value>
      <webElementGuid>c4fa39fd-52a1-4b9d-926c-86c77ddd92da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Select City *</value>
      <webElementGuid>c119cd67-f1b5-44ad-95a7-deb431ee5c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-none-selected-text</name>
      <type>Main</type>
      <value>Select City</value>
      <webElementGuid>ae9c1dbf-d06f-4f34-a989-b0617778e321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select City *AgasteeswaramAlangudiAlangulamAmbasamudramAnaimalaiAndipattiAndippattiAnnavasalArakkonamAraniAranthangiAravakurichiArcotAriyalurAruppukkottaiAtturAvadiAvinashiAvudaiyarkoilBargurBhavaniBodinayakanurChengalpattuChengamChennaiCherangodeCheyurCheyyarChidambaramChidambaram NorthChinnasalemCoimbatoreCoimbatore NorthCoimbatore SouthCoonoorCuddaloreDenkanikottaiDevakottaiDharapuramDharmapuriDindigulDusiErodeEttaiyapuramGandarvakkottaiGangavalliGingeeGobichettipalayamGudalurGudiyattamGummudipoondiGunambadiHarurHosurIdappadiIlayangudiIlluppurJayamkondacholapuramKadaladiKadambarayapattiKadamburKalkulamKallakurichiKamudiKamuthiKanchipuramKangayamKanyakumariKaraikudiKaraipudurKariapattiKarurKatpadiKattumannarkoilKattuputhurKaveripattinamKilvelurKodaikanalKoradacheriKotagiriKothamangalam NorthKovilpattiKrishnagiriKrishnarayapuramKudavasalKulathurKulithalaiKumarapuramKumbakonamKundahKuttalamKuzhithuraiLalgudiMadhavapuramMaduraiMadurai NorthMadurai SouthMadurantakamMallapuramMallasamudramManamaduraiManamelkudiManapparaiMannachanallurMannargudiMarakkanamMayiladuthuraiMelurMettupalayamMetturMoongilpattiMusiriMuthukulathurNaduppatiNagapattinamNagercoilNallampalliNamakkalNanguneriNannilamNathamNidamangalamNilakottaiNilgirisOddanchatramOmalurOotyOrathanaduOttapidaramPadapaiPalacodePalaniPalayamkottaiPalayanurPalladamPallipalayamPallipattuPandalurPanrutiPapanasamPappireddipattiParamakudiParamathiPattukkottaiPauparapattiPavithiramPennagaramPennathurPeraiyurPerambalurPeravuraniPeriyakulamPerunduraiPillaPalayamPochampalliPollachiPolurPonneriPudukkottaiPuliampattiPullagoundampattiRadhapuramRajapalayamRamanathapuramRamapuramRameswaramRasipuramRayagiriS RamachandrapuramSakkottaiSalemSankarankovilSankarapuramSankariSathankulamSathyamangalamSatturSenduraiSengaluneer ThottamShenkottaiSholavandanSholayar Dam CitySingampunariSirkazhiSivagangaSivagiriSivakasiSoodamaniSriperumbudurSrivaikuntamSrivilliputhurTenkasiThandalaiThandrambattuThandrampattuThanjavurTharangambadiTheniThirukkuvalaiThirukoilureThirumakkottai -IIThirumayamThirupananthalThiruthaniThiruthuraipoondiThiruvadanaiThiruvaiyaruThiruvarurThiruvidaimaruthurThoothukudiThoothukudi (Tuticorin)ThottiyamThovalaiThuraikkaduThuraiyurTindivanamTiruchendurTiruchengodeTiruchirappalliTiruchuliTirukazhukundramTirumangalamTirunelveliTirupatturTiruppurTiruppuvanamTiruvallurTiruvannamalaiTiruvarurTittagudiTuraiyurUdayarpalayamUdumalpetUllarUlundurpetUsilampattiUthamapalayamUthangaraiUthukkottaiUttangaraiUttiramerurVadipattiVairavanpattiValangaimanValappadiValparaiVanadirayanpattiVandalur R.F.VandavasiVaniyambadiVanurVedaranyamVedasandurVeerakeralampudurVellaloreVelloreVelurVennangupattuVeppanthattaiVilathikulamVilavancodeVillupuramViriyurVirudhachalamVirudhunagarWalajapetWallajahYercaudZ.Devarkulam</value>
      <webElementGuid>2fa35842-dc0a-40f0-a3c2-d10fe715bb07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CityId&quot;)</value>
      <webElementGuid>e998b6d7-0930-401d-98f2-cd72ca993dd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='CityId']</value>
      <webElementGuid>f245a971-8587-4c93-b709-c972516da9f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerForm']/div[2]/div[5]/select</value>
      <webElementGuid>94168872-d801-4d83-90d3-12b511cbae76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/preceding::select[4]</value>
      <webElementGuid>65405820-5cb1-4cb9-98ca-3ba8cf101950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I agree to receive information by signing up on Kalasalingam Academy of Research and Education *'])[1]/preceding::select[4]</value>
      <webElementGuid>02c59900-75b6-4e03-8d7c-ac6abe8bf0d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/select</value>
      <webElementGuid>35373cd8-df21-4b27-acbd-7a1748e0f808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'city_id' and @id = 'CityId' and (text() = 'Select City *AgasteeswaramAlangudiAlangulamAmbasamudramAnaimalaiAndipattiAndippattiAnnavasalArakkonamAraniAranthangiAravakurichiArcotAriyalurAruppukkottaiAtturAvadiAvinashiAvudaiyarkoilBargurBhavaniBodinayakanurChengalpattuChengamChennaiCherangodeCheyurCheyyarChidambaramChidambaram NorthChinnasalemCoimbatoreCoimbatore NorthCoimbatore SouthCoonoorCuddaloreDenkanikottaiDevakottaiDharapuramDharmapuriDindigulDusiErodeEttaiyapuramGandarvakkottaiGangavalliGingeeGobichettipalayamGudalurGudiyattamGummudipoondiGunambadiHarurHosurIdappadiIlayangudiIlluppurJayamkondacholapuramKadaladiKadambarayapattiKadamburKalkulamKallakurichiKamudiKamuthiKanchipuramKangayamKanyakumariKaraikudiKaraipudurKariapattiKarurKatpadiKattumannarkoilKattuputhurKaveripattinamKilvelurKodaikanalKoradacheriKotagiriKothamangalam NorthKovilpattiKrishnagiriKrishnarayapuramKudavasalKulathurKulithalaiKumarapuramKumbakonamKundahKuttalamKuzhithuraiLalgudiMadhavapuramMaduraiMadurai NorthMadurai SouthMadurantakamMallapuramMallasamudramManamaduraiManamelkudiManapparaiMannachanallurMannargudiMarakkanamMayiladuthuraiMelurMettupalayamMetturMoongilpattiMusiriMuthukulathurNaduppatiNagapattinamNagercoilNallampalliNamakkalNanguneriNannilamNathamNidamangalamNilakottaiNilgirisOddanchatramOmalurOotyOrathanaduOttapidaramPadapaiPalacodePalaniPalayamkottaiPalayanurPalladamPallipalayamPallipattuPandalurPanrutiPapanasamPappireddipattiParamakudiParamathiPattukkottaiPauparapattiPavithiramPennagaramPennathurPeraiyurPerambalurPeravuraniPeriyakulamPerunduraiPillaPalayamPochampalliPollachiPolurPonneriPudukkottaiPuliampattiPullagoundampattiRadhapuramRajapalayamRamanathapuramRamapuramRameswaramRasipuramRayagiriS RamachandrapuramSakkottaiSalemSankarankovilSankarapuramSankariSathankulamSathyamangalamSatturSenduraiSengaluneer ThottamShenkottaiSholavandanSholayar Dam CitySingampunariSirkazhiSivagangaSivagiriSivakasiSoodamaniSriperumbudurSrivaikuntamSrivilliputhurTenkasiThandalaiThandrambattuThandrampattuThanjavurTharangambadiTheniThirukkuvalaiThirukoilureThirumakkottai -IIThirumayamThirupananthalThiruthaniThiruthuraipoondiThiruvadanaiThiruvaiyaruThiruvarurThiruvidaimaruthurThoothukudiThoothukudi (Tuticorin)ThottiyamThovalaiThuraikkaduThuraiyurTindivanamTiruchendurTiruchengodeTiruchirappalliTiruchuliTirukazhukundramTirumangalamTirunelveliTirupatturTiruppurTiruppuvanamTiruvallurTiruvannamalaiTiruvarurTittagudiTuraiyurUdayarpalayamUdumalpetUllarUlundurpetUsilampattiUthamapalayamUthangaraiUthukkottaiUttangaraiUttiramerurVadipattiVairavanpattiValangaimanValappadiValparaiVanadirayanpattiVandalur R.F.VandavasiVaniyambadiVanurVedaranyamVedasandurVeerakeralampudurVellaloreVelloreVelurVennangupattuVeppanthattaiVilathikulamVilavancodeVillupuramViriyurVirudhachalamVirudhunagarWalajapetWallajahYercaudZ.Devarkulam' or . = 'Select City *AgasteeswaramAlangudiAlangulamAmbasamudramAnaimalaiAndipattiAndippattiAnnavasalArakkonamAraniAranthangiAravakurichiArcotAriyalurAruppukkottaiAtturAvadiAvinashiAvudaiyarkoilBargurBhavaniBodinayakanurChengalpattuChengamChennaiCherangodeCheyurCheyyarChidambaramChidambaram NorthChinnasalemCoimbatoreCoimbatore NorthCoimbatore SouthCoonoorCuddaloreDenkanikottaiDevakottaiDharapuramDharmapuriDindigulDusiErodeEttaiyapuramGandarvakkottaiGangavalliGingeeGobichettipalayamGudalurGudiyattamGummudipoondiGunambadiHarurHosurIdappadiIlayangudiIlluppurJayamkondacholapuramKadaladiKadambarayapattiKadamburKalkulamKallakurichiKamudiKamuthiKanchipuramKangayamKanyakumariKaraikudiKaraipudurKariapattiKarurKatpadiKattumannarkoilKattuputhurKaveripattinamKilvelurKodaikanalKoradacheriKotagiriKothamangalam NorthKovilpattiKrishnagiriKrishnarayapuramKudavasalKulathurKulithalaiKumarapuramKumbakonamKundahKuttalamKuzhithuraiLalgudiMadhavapuramMaduraiMadurai NorthMadurai SouthMadurantakamMallapuramMallasamudramManamaduraiManamelkudiManapparaiMannachanallurMannargudiMarakkanamMayiladuthuraiMelurMettupalayamMetturMoongilpattiMusiriMuthukulathurNaduppatiNagapattinamNagercoilNallampalliNamakkalNanguneriNannilamNathamNidamangalamNilakottaiNilgirisOddanchatramOmalurOotyOrathanaduOttapidaramPadapaiPalacodePalaniPalayamkottaiPalayanurPalladamPallipalayamPallipattuPandalurPanrutiPapanasamPappireddipattiParamakudiParamathiPattukkottaiPauparapattiPavithiramPennagaramPennathurPeraiyurPerambalurPeravuraniPeriyakulamPerunduraiPillaPalayamPochampalliPollachiPolurPonneriPudukkottaiPuliampattiPullagoundampattiRadhapuramRajapalayamRamanathapuramRamapuramRameswaramRasipuramRayagiriS RamachandrapuramSakkottaiSalemSankarankovilSankarapuramSankariSathankulamSathyamangalamSatturSenduraiSengaluneer ThottamShenkottaiSholavandanSholayar Dam CitySingampunariSirkazhiSivagangaSivagiriSivakasiSoodamaniSriperumbudurSrivaikuntamSrivilliputhurTenkasiThandalaiThandrambattuThandrampattuThanjavurTharangambadiTheniThirukkuvalaiThirukoilureThirumakkottai -IIThirumayamThirupananthalThiruthaniThiruthuraipoondiThiruvadanaiThiruvaiyaruThiruvarurThiruvidaimaruthurThoothukudiThoothukudi (Tuticorin)ThottiyamThovalaiThuraikkaduThuraiyurTindivanamTiruchendurTiruchengodeTiruchirappalliTiruchuliTirukazhukundramTirumangalamTirunelveliTirupatturTiruppurTiruppuvanamTiruvallurTiruvannamalaiTiruvarurTittagudiTuraiyurUdayarpalayamUdumalpetUllarUlundurpetUsilampattiUthamapalayamUthangaraiUthukkottaiUttangaraiUttiramerurVadipattiVairavanpattiValangaimanValappadiValparaiVanadirayanpattiVandalur R.F.VandavasiVaniyambadiVanurVedaranyamVedasandurVeerakeralampudurVellaloreVelloreVelurVennangupattuVeppanthattaiVilathikulamVilavancodeVillupuramViriyurVirudhachalamVirudhunagarWalajapetWallajahYercaudZ.Devarkulam')]</value>
      <webElementGuid>045cb816-b969-4070-a75a-c864c87dc362</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
