<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ViewDownload</name>
   <tag></tag>
   <elementGuidId>958c91cc-5515-4a2b-afb7-35f8e0dcea1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='newsletters']/div/div/div/p/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.dwnloadlnk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;View/Download&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4342a96d-c819-49f6-9357-2bcd8162466b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dwnloadlnk</value>
      <webElementGuid>238a645a-5b09-4eae-9c9f-795165fc73ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>e6f08c30-ae05-4510-b2a2-f5cd5cebfc12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://kalasalingam.ac.in/aicte-letter-of-approval/</value>
      <webElementGuid>5c13ced2-7c21-4b0e-a2fd-8f72cda9aa22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener</value>
      <webElementGuid>4ea446f2-0e33-4bae-8808-2dc3ab59639c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View/Download</value>
      <webElementGuid>d3fecec4-bc4c-40c2-8043-b92089c27fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;wsmenucontainer&quot;]/div[@class=&quot;wrapper&quot;]/div[@id=&quot;newsletters&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;courcesublst&quot;]/div[@class=&quot;lstloop&quot;]/p[1]/a[@class=&quot;dwnloadlnk&quot;]</value>
      <webElementGuid>00f6a4cd-f4c1-4638-b0bc-8bbfd3a56a32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='newsletters']/div/div/div/p/a</value>
      <webElementGuid>c7af9af0-a19b-485f-9277-685ccc9c09da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View/Download')]</value>
      <webElementGuid>edeea897-ebe6-4e50-8046-1a2690b817a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AICTE Approvals'])[2]/following::a[1]</value>
      <webElementGuid>ce091e00-a1c4-413f-b8cf-ba4d00eea2d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AICTE Approvals'])[1]/following::a[1]</value>
      <webElementGuid>3bcb8e24-d4cd-4d3d-ae56-85b1435b13e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NAAC SSR'])[1]/preceding::a[1]</value>
      <webElementGuid>70875120-e214-4f87-aea7-e8852499e6b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View/Download'])[2]/preceding::a[1]</value>
      <webElementGuid>9eaa7bec-3cf1-448f-a9f3-da154df65447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View/Download']/parent::*</value>
      <webElementGuid>dc7a64b8-c9ef-4840-af99-58f03b923589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://kalasalingam.ac.in/aicte-letter-of-approval/')]</value>
      <webElementGuid>211c6a8d-30a7-47bf-b7c6-8a64f3e04ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/p/a</value>
      <webElementGuid>e74b406e-b387-497d-b4d9-1ed2138bf2ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://kalasalingam.ac.in/aicte-letter-of-approval/' and (text() = 'View/Download' or . = 'View/Download')]</value>
      <webElementGuid>cece36e7-2d5b-4343-b6ae-a219a199c3f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
