<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_New Registration_email_regn</name>
   <tag></tag>
   <elementGuidId>c34051e6-1b53-43f9-883f-880cc97a2d09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email_regn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email_regn&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Email&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0bc63206-0f0f-4cb4-9e89-96908d3010c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control placeholder-no-fix</value>
      <webElementGuid>b4ccce3a-db48-4be0-b22c-b4a400c36151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5bf4e062-8762-4eed-a37a-a3bd547951cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8c5d4163-7070-4aec-ac5f-d45b2697b2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>fa6369b0-9fb9-4722-bf9e-7d876f2369ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email_regn</value>
      <webElementGuid>3a935349-cf14-4edb-ab3d-cd7c641b8d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[@class=&quot;login&quot;]/div[@class=&quot;content&quot;]/form[@class=&quot;register-form&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;input-icon&quot;]/input[@class=&quot;form-control placeholder-no-fix&quot;]</value>
      <webElementGuid>65477e3f-589b-4263-a2b0-a1604aa22081</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email_regn']</value>
      <webElementGuid>a34db2f8-8e1f-477d-b9a9-40246a426dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[3]/div/div/input</value>
      <webElementGuid>a394bba5-a25c-42b1-97a3-7eee3ef5ffc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Email' and @name = 'email_regn']</value>
      <webElementGuid>77f7db0e-a081-4faa-b0fd-0eebfd2b96a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
