<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_ng-pristine ng-untouched ng-val_f6b59a</name>
   <tag></tag>
   <elementGuidId>cfb55f65-4dd8-43be-a6ef-271817d94722</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ng-pristine.ng-untouched.ng-valid.ng-scope.ng-empty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search among 7126 Kalasalingamites...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce3bef61-7310-4706-83c3-0e2f51a3effb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c50a0b41-4449-4447-b356-340b4437beb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>state.keyword</value>
      <webElementGuid>69220b88-9e64-4731-b833-1a383376c53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ac-enter</name>
      <type>Main</type>
      <value>triggerKeywordSearch()</value>
      <webElementGuid>d4a85d6a-8742-45f2-8803-015e6ebf3b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search among 7126 Kalasalingamites...</value>
      <webElementGuid>59187fa6-d98b-4f44-8dc9-d368c578ed93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-scope ng-empty</value>
      <webElementGuid>2750f890-2c38-4477-875b-3a9ac8aef6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alumni-page&quot;)/body[@class=&quot;body&quot;]/div[3]/div[@class=&quot;page_layout&quot;]/div[@class=&quot;main_column&quot;]/div[@class=&quot;js_seo_directory ng-scope&quot;]/div[1]/div[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;ac_large_search_box&quot;]/div[1]/input[@class=&quot;ng-pristine ng-untouched ng-valid ng-scope ng-empty&quot;]</value>
      <webElementGuid>377ab966-e9e1-4dfb-8565-c89fb7681040</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>ff2e2707-2622-4015-8dd2-80496085fb44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='alumni-page']/body/div[3]/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>8c114a8c-1926-4813-83fc-006d3fd5f8eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>89630ec8-e3be-476b-bd66-d1991a9dbf49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search among 7126 Kalasalingamites...']</value>
      <webElementGuid>d4b25ae5-f69f-4670-808a-33deaf284707</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
