<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download</name>
   <tag></tag>
   <elementGuidId>a59803a9-8295-427f-9396-7867611cad22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Download')])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.dwnloadlnk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Download&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3603d846-2f28-40cc-9f1d-5c3e5cd07d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dwnloadlnk</value>
      <webElementGuid>147cb07a-31ec-4fd7-a68a-d38faf5eb85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wp-content/uploads/2022/07/Hostel-Rules.pdf</value>
      <webElementGuid>108a49aa-1ca4-4a42-b9cd-fbd7a4c3a5e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download</value>
      <webElementGuid>c5ff1687-d4a9-4f2c-bdb3-8f24a3f80ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;wsmenucontainer&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;sectiontab recruiters sportssec darkgraybg ctssposec&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;courcesublst&quot;]/div[@class=&quot;lstloop&quot;]/p[1]/a[@class=&quot;dwnloadlnk&quot;]</value>
      <webElementGuid>2a23a0e6-d346-4275-bbda-2531c65f6ef2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Download')])[3]</value>
      <webElementGuid>451da7b9-375d-4ccb-a660-db9abcdd47ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hostel Rules and Regulations'])[1]/following::a[1]</value>
      <webElementGuid>a9e130d6-2232-4c14-a4ac-1a673441f654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hostel Rules'])[1]/following::a[1]</value>
      <webElementGuid>5a47f5f3-17ae-4780-9454-1d57df997513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enquire Now!'])[1]/preceding::a[1]</value>
      <webElementGuid>48a416a3-52e5-406d-931d-1008f3d44f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enquiry Form'])[1]/preceding::a[1]</value>
      <webElementGuid>7cd0b3bb-00de-4439-9ed7-825caf0a7dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download']/parent::*</value>
      <webElementGuid>9a50957c-f675-4c4f-b0ec-595f9b9ed001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/wp-content/uploads/2022/07/Hostel-Rules.pdf')]</value>
      <webElementGuid>1142a3eb-b443-4503-bdf9-05cd45195cf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/p/a</value>
      <webElementGuid>87110acf-28f5-4f5a-a618-39f55120f9a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wp-content/uploads/2022/07/Hostel-Rules.pdf' and (text() = 'Download' or . = 'Download')]</value>
      <webElementGuid>d614d348-3aed-40e8-b791-35ebd2b2467b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
