<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tel. 04563 289042_hamb-top</name>
   <tag></tag>
   <elementGuidId>a2a0e718-313d-4fb4-b9d6-ecc7256266fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.hamb-top</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.hamburger</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>05cd04d4-e2f9-4c8f-a80d-c0723286f114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hamb-top</value>
      <webElementGuid>b561521f-a951-4890-949f-9a15f22080ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;wsmenucontainer&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;topheader&quot;]/div[@class=&quot;largecontainer&quot;]/div[@class=&quot;row&quot;]/button[@class=&quot;hamburger animated fadeInLeft is-closed&quot;]/span[@class=&quot;hamb-top&quot;]</value>
      <webElementGuid>5082ecf8-e9b9-4649-9376-4756553d2832</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>adf7d3b3-7760-4ee4-8e41-114bd98f18cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
