<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter any User Name and Password_user_name</name>
   <tag></tag>
   <elementGuidId>985f2c94-3624-440b-9b20-2ecdf649875c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='user_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;user_name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;User Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5cb93b0-eaa3-4f06-8c6b-c83ec6309432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-solid placeholder-no-fix form-group required</value>
      <webElementGuid>13a1737a-8994-490d-9344-c2e8aec7e63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cb47b860-5369-4b72-8aba-40d45543eaff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>95a95fb1-f392-49b1-bc74-949217564d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>User Name</value>
      <webElementGuid>8591d551-180c-4b06-a783-07466bbbb52d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_name</value>
      <webElementGuid>c982b2c4-a12e-4d5b-af29-b880cad2bc1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>010b4055-5d59-4506-9c30-c3e0e8aec3e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login&quot;]/div[@class=&quot;user-login-5&quot;]/div[@class=&quot;row bs-reset&quot;]/div[@class=&quot;col-md-6 login-container bs-reset&quot;]/div[@class=&quot;login-content&quot;]/form[@class=&quot;login-form&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-6&quot;]/div[@class=&quot;marginb&quot;]/input[@class=&quot;form-control form-control-solid placeholder-no-fix form-group required&quot;]</value>
      <webElementGuid>9fc31232-f07b-495a-a1fb-689aa8cdf821</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='user_name']</value>
      <webElementGuid>0ea8e6fc-7b6f-4f97-8c74-f089405f7824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>af08cf72-06a6-4add-bb20-855669ca96b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'User Name' and @name = 'user_name']</value>
      <webElementGuid>befa31d2-8f43-4ec3-9aa6-a1b72514d9eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
