<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span</name>
   <tag></tag>
   <elementGuidId>c6bba1dc-a4f8-494c-99b3-ec8cb00a63ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.rememberme.mt-checkbox.mt-checkbox-outline > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>label span</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b9ddee54-b5a7-4038-8800-1cd691a9e770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login&quot;]/div[@class=&quot;user-login-5&quot;]/div[@class=&quot;row bs-reset&quot;]/div[@class=&quot;col-md-6 login-container bs-reset&quot;]/div[@class=&quot;login-content&quot;]/form[@class=&quot;login-form&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-4&quot;]/div[@class=&quot;rem-password&quot;]/label[@class=&quot;rememberme mt-checkbox mt-checkbox-outline&quot;]/span[1]</value>
      <webElementGuid>b8667ae4-3818-4c6c-9ff0-4843c012fb33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>a72545dd-1adb-4648-b821-7ab0f11e891b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
