<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ranking</name>
   <tag></tag>
   <elementGuidId>55e3e3b9-0e53-40c2-8253-5253848979bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Ranking')])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.accreditationmnu > ul.row.sub-menu.twocolum > div.innermenuitem > div.row > div.col-sm-3 > ul > li:nth-of-type(3) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Ranking&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bb6ccbbf-49c5-4e92-98ba-db7c0a6ad719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://kalasalingam.ac.in/accrediation-ranking</value>
      <webElementGuid>aab359a0-c65d-477f-8e84-c22be3931b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ranking</value>
      <webElementGuid>5bf8c364-2e77-4d1b-8611-16acad905b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;wsmenucontainer&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;middlediv wsmenucontainer clearfix&quot;]/div[@class=&quot;header sticky stick-me not-sticking&quot;]/div[@class=&quot;largecontainer&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-9 navigation text-right&quot;]/nav[@class=&quot;wsmenu clearfix&quot;]/ul[@class=&quot;wsmenu-list&quot;]/li[@class=&quot;accreditationmnu&quot;]/ul[@class=&quot;row sub-menu twocolum&quot;]/div[@class=&quot;innermenuitem&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-3&quot;]/ul[1]/li[3]/a[1]</value>
      <webElementGuid>96a0815d-dd06-4bbe-b329-69583de3bac5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Ranking')])[2]</value>
      <webElementGuid>cc525dbf-d2e1-49d1-ae3b-73ebcb0a1698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accreditation to KARE'])[1]/following::a[1]</value>
      <webElementGuid>34668726-47fc-4549-8a0a-e185feb6b519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[6]/following::a[2]</value>
      <webElementGuid>940ecf9f-344a-426e-9c57-6e1ca184eee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IQAC'])[2]/preceding::a[1]</value>
      <webElementGuid>58173fe4-3eb2-49ec-8c6e-0878b7be62dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Newsletters'])[1]/preceding::a[2]</value>
      <webElementGuid>13ff0db4-0dbd-46de-99d2-116fd449c3fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ranking']/parent::*</value>
      <webElementGuid>bfcd9d8a-fc44-490b-9220-1c33fc7bd59d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://kalasalingam.ac.in/accrediation-ranking')]</value>
      <webElementGuid>caa4531e-25af-4cc5-959e-bcb89d58cb54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/ul/div/div/div/ul/li[3]/a</value>
      <webElementGuid>90326d97-e14e-4967-aaf0-1c7e1c0088b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://kalasalingam.ac.in/accrediation-ranking' and (text() = 'Ranking' or . = 'Ranking')]</value>
      <webElementGuid>d4915616-4ff6-4933-9e4d-c0e3dfe2e9b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
