<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Swimming Pool Rules  Regulations</name>
   <tag></tag>
   <elementGuidId>72920b1f-d88f-4fb3-8f32-bc547f9bfbf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[21]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#heading7 > h4.mb-0 > button.btn.btn-link.collapsed</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Swimming Pool Rules &amp; Regulations&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e7d49dab-f1e1-4569-83d4-e60381a3ee06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fce5110b-1095-42cd-8b6c-a073adb32888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-link collapsed</value>
      <webElementGuid>a7c00506-676f-4593-ab30-f01504003d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>71f88583-06b2-4fdc-a8af-6f493493d7d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#collapse7</value>
      <webElementGuid>73fdb691-7be7-4bc4-9c64-e4121f9961af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Swimming Pool Rules &amp; Regulations</value>
      <webElementGuid>9c038fcf-c0a0-4b93-8114-8d63f35b5b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;heading7&quot;)/h4[@class=&quot;mb-0&quot;]/button[@class=&quot;btn btn-link collapsed&quot;]</value>
      <webElementGuid>1af9c904-239b-434d-a08c-c77056fc73ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[21]</value>
      <webElementGuid>9d5e66e6-e361-409d-9758-0dea21e2ec26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='heading7']/h4/button</value>
      <webElementGuid>0981f54c-7a90-4659-a66c-145242a055ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='›'])[3]/following::button[7]</value>
      <webElementGuid>fb8ee442-51c4-4131-afc6-cec1c5dc254a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='‹'])[3]/following::button[8]</value>
      <webElementGuid>a9a35109-baed-4b1c-8fe0-f80955cf0601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The right of admission is reserved.'])[1]/preceding::button[1]</value>
      <webElementGuid>f7b82a52-0ffb-4aa0-9915-73b3054b7782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Right of termination of membership for misconduct default or any other reason is reserved.'])[1]/preceding::button[1]</value>
      <webElementGuid>f5f8477b-bef1-4ad2-8a27-9ac7ad708120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Swimming Pool Rules &amp; Regulations']/parent::*</value>
      <webElementGuid>c3a19eda-49cc-4281-85e9-3d8c206f379d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/h4/button</value>
      <webElementGuid>00554ff6-73b4-45a3-9538-ff15d992bb40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Swimming Pool Rules &amp; Regulations' or . = 'Swimming Pool Rules &amp; Regulations')]</value>
      <webElementGuid>2a5feda7-040d-4525-bad7-7b5917abd7ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
