<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sports Achievements</name>
   <tag></tag>
   <elementGuidId>8ea75989-f386-4cf3-9fdb-2718b187bbf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[22]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#heading8 > h4.mb-0 > button.btn.btn-link.collapsed</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Sports Achievements&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a533f651-4e06-4ca8-9181-299319e97f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e422f996-e976-4703-b885-152d851fa9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-link collapsed</value>
      <webElementGuid>a9158fe4-45dc-4bdc-b314-e78cec2f22f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>894981be-c11e-4c52-94d3-b3f47b93c2bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#collapse8</value>
      <webElementGuid>14350807-1121-4b4a-a219-24f48f0ee7ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sports Achievements</value>
      <webElementGuid>2fc770f4-4613-45c3-8775-58357ad531b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;heading8&quot;)/h4[@class=&quot;mb-0&quot;]/button[@class=&quot;btn btn-link collapsed&quot;]</value>
      <webElementGuid>b34d4bce-ec55-47c2-a9d0-20d8af32a76b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[22]</value>
      <webElementGuid>8bb3e8fa-c7e4-493d-92d0-096278e0e553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='heading8']/h4/button</value>
      <webElementGuid>01476c0d-d571-4bae-967e-497a6ee3152d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Swimming pool should be used in hygienic manner.'])[1]/following::button[1]</value>
      <webElementGuid>b5eb8314-47c8-44ba-a165-8eed40212faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Horse play not allowed in the pool'])[1]/following::button[1]</value>
      <webElementGuid>796e9e90-7290-473c-b5a0-a1884c547914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yoga Achievements'])[1]/preceding::button[1]</value>
      <webElementGuid>1f151f76-2106-4e47-89df-b359afcea5b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YOGA ACHIEVEMENTS 2023-2024'])[1]/preceding::button[1]</value>
      <webElementGuid>81e289a6-4f75-4ef6-921e-7bb7bfef1a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sports Achievements']/parent::*</value>
      <webElementGuid>f050091e-ca05-4f6c-beb1-0f897108103a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div[3]/div/h4/button</value>
      <webElementGuid>174754f7-cf6c-4e6f-84b1-25674abc6e77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Sports Achievements' or . = 'Sports Achievements')]</value>
      <webElementGuid>1c82ed6c-0ac5-4b2c-9409-9e32148731b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
