<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Placements</name>
   <tag></tag>
   <elementGuidId>ecb963a8-40f6-43d5-a614-5168293b953b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Placements')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.wsmenu-list > li:nth-of-type(7) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Placements&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4ac2dbd8-b733-4732-a62d-6ac1d91d5967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://kalasalingam.ac.in/placement</value>
      <webElementGuid>07e1e3f3-7160-47e0-9b10-42f71849f516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Placements</value>
      <webElementGuid>4c149113-c309-4ff6-b00c-c38068055633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;wsmenucontainer&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;middlediv wsmenucontainer clearfix&quot;]/div[@class=&quot;header sticky stick-me not-sticking&quot;]/div[@class=&quot;largecontainer&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-9 navigation text-right&quot;]/nav[@class=&quot;wsmenu clearfix&quot;]/ul[@class=&quot;wsmenu-list&quot;]/li[7]/a[1]</value>
      <webElementGuid>db96bcc8-7555-40cd-80a1-769925e2983f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Placements')]</value>
      <webElementGuid>8e10c77f-06f9-4c7c-9913-e9ef281d5e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feedback'])[2]/following::a[1]</value>
      <webElementGuid>3465ae4e-c8c9-4798-bfd1-f217ba1ea0d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AR login'])[1]/following::a[2]</value>
      <webElementGuid>b9955582-3a8f-4440-aeaa-00cbdcad7dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[7]/preceding::a[1]</value>
      <webElementGuid>d63c80be-df1e-41b3-a978-176ddc63e732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dream offer'])[1]/preceding::a[2]</value>
      <webElementGuid>25949a33-b9e6-4806-a53d-c9c7cb08ea57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Placements']/parent::*</value>
      <webElementGuid>2d5d2737-6806-4350-880b-35d1691ffc64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://kalasalingam.ac.in/placement')]</value>
      <webElementGuid>e077201b-10db-45e4-91b8-b9b531990a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[7]/a</value>
      <webElementGuid>1aef0bae-255b-4be9-ac2d-d22ba59e058e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://kalasalingam.ac.in/placement' and (text() = 'Placements' or . = 'Placements')]</value>
      <webElementGuid>2abcad5f-d613-4a80-b19c-57147c951f92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
