<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close</name>
   <tag></tag>
   <elementGuidId>a0bf5225-afbc-4d02-a317-5dac2ea0c1ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-secondary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Electrical &amp; Electronics\n        \n          ×\n        \n      \n\n      \nDC &amp; AC  Machines Laboratory\nIt is to expose the students the techniques of designing and building power electronics circuits. Our laboratory is fully equipped with advanced Power electronic circuits and modules like three phase IGBT based inverter, DC-DC converter, MOSFET Chopper. The nature of power electronic circuits requires that the laboratory course be handled in a way different from the conventional laboratory approach. This lab is also used to conduct experiments in the domain of digital electronics. This lab is self sufficient in all respects. Each standard setup in the lab consists of basic and advanced trainer kits, oscilloscope and function generators. For enhancing the research work, intelligent power module is equipped through which simulation based experiments can be carried out.\n\nApplied Electronics Laboratory\nThe Applied Electronics Lab is equipped with all necessary devices, components and instruments required for doing experiments related to basic electronics, digital and integrated circuits. The role of this laboratory is to educate students in the concepts and techniques of Electronics Systems,   analogue components and integrated circuits. This lab has DC supplies, CROs, 5 in 1 test lab, Dual trace CRO, 4 trace CRO, Audio Power Meter, Components and IC tester, Linear IC Tester, DSO, etc. are made available in this laboratory.\n\nPower Electronics Laboratory\nIt is to expose the students the techniques of designing and building power electronics circuits. Our laboratory is fully equipped with advanced Power electronic circuits and modules like three phase IGBT based inverter, DC-DC converter, MOSFET Chopper. The nature of power electronic circuits requires that the laboratory course be handled in a way different from the conventional laboratory approach. This lab is also used to conduct experiments in the domain of digital electronics. This lab is self sufficient in all respects. Each standard setup in the lab consists of basic and advanced trainer kits, oscilloscope and function generators. For enhancing the research work, intelligent power module is equipped through which simulation based experiments can be carried out.\n\nMeasurements and Control Laboratory\nThe laboratory established with testing and measuring instruments like DMMs, Tachometer, Stepper Motor Trainer, AC/DC Servo motor trainers, Magnetic amplifier kit which provides in-depth training to the students. This lab is general enough to hold a number of experiments suitable for giving students enough exposure to enable them to easily adopt experiments in more advanced laboratories in the department.\n\nRenewable Energy Technology Laboratory\nRenewable Energy Laboratory has conduct research in all aspects of Energy conservation and Renewable Energy Technologies. In this laboratory researchers and students have worked on solar and wind technology based projects. This Laboratory focuses on creative answers to today’s energy challenges. Energy researchers are transforming the way the nation and the world use energy. The major facilities available in the laboratory are MPP tracking system, Solar distillation system, Solar cooker, Solar pumping system, Thermo anemometer, 50W Solar PV Panel, Digital Lux Meter, 1KW Solar PV Array, DC-DC Converter, Battery Bank and Solar PV Emulator.\n\nPower System Simulation Laboratory\nThe power system simulation laboratory is equipped with matlab software which is helping the students and researchers to implement the advanced techniques in power systems such as phenomena for simulation; simulation techniques; role of physical models; system size needed; transmission modeling techniques; transformer modeling techniques; machine modeling techniques; protection, and control.\n\nIntel Intelligence Systems Laboratory\nThis laboratory has been set-up at KARE campus with the technical support of INTEL India and FICE, Bangalore with a view to enhance the students and faculty member’s knowledge on embedded system and Internet of Things (IoT). The facilities available in the INTEL Laboratory are Computers with i7 processors, Intel® Galileo Generation2 Kits, Advance Sensor Set for Arduino-DF Robot, Wi-Fi Antenna, GSM/GPRS shield – ATWIN Quad-band GPRS/GSM Shield for Arduino, Arduino IDE and Intel XDK IoT Edition.\n\nKARE-NI Technology Innovation Laboratory\nThe center is an initiative of National Instruments which strives to increase the employability of students. The center is the authorized center to provide hands on training in Lab VIEW for students and faculty members. The following facilities are available in the center are ELVIS, Lab VIEW, MyDAQ, My RIO, CRIO, CDAQ, FPGA Board and etc., ELVIS Optical Communication board, Telecommunication board. In our department 25 students are successfully completed CLAD certification.\n\n\n\n        Close&quot;i >> internal:text=&quot;Close&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>08ad15a5-56d6-45a8-b0fd-7c97a9f30fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>97a2107d-abf3-4590-93fd-48b5538307d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary</value>
      <webElementGuid>92b8460d-35a1-471b-9520-d0d4101b723c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>0cdbc168-411b-42e4-a1bc-e417fb5e3b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>e7ac2837-ae23-40cc-98e4-a77ab34c6dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Lab1&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-footer&quot;]/button[@class=&quot;btn btn-secondary&quot;]</value>
      <webElementGuid>e6a773dc-3db0-4c2a-9974-cf7e95a95f03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>8f644797-8464-4ad4-bf3c-cf00a33c6a58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Lab1']/div/div/div[3]/button</value>
      <webElementGuid>661fcdce-9181-4e4f-a71c-dde848d4a64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KARE-NI Technology Innovation Laboratory'])[1]/following::button[1]</value>
      <webElementGuid>a7077852-6480-4e85-9e15-25256a9a91fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intel Intelligence Systems Laboratory'])[1]/following::button[1]</value>
      <webElementGuid>19b47591-f518-4c84-9d6b-b4e2786aa5af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agriculture'])[1]/preceding::button[1]</value>
      <webElementGuid>58bf3e80-e677-427d-85e1-cf4d51a4865a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Close']/parent::*</value>
      <webElementGuid>e04b7740-6653-4f0a-bc0a-7d81ccfbde1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[3]/button</value>
      <webElementGuid>318d8a5b-7a3f-4e30-b1c7-8ed693436e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>7001b4bc-a31e-4611-8cfa-adfe4b15ae46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
