<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download</name>
   <tag></tag>
   <elementGuidId>896f93af-28c1-47be-b01f-eb541cdfc1fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Download')])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.dwnloadlnk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Download&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>793dc703-deb6-49c5-9b0e-72b047fdc640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dwnloadlnk</value>
      <webElementGuid>f6755b18-631c-443f-81a1-d967b5b80f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>d20bca2d-e90e-4faa-959c-ed411649bcaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://kalasalingam.ac.in/wp-content/uploads/Curriculum/B.SC_COMPUTER%20SCIENCE_2021.pdf</value>
      <webElementGuid>6175725e-7d82-4a81-a4eb-e4ec712822b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener</value>
      <webElementGuid>096148f9-cf06-42d3-aa9b-e037188167d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download</value>
      <webElementGuid>fd4936b9-0f67-4a6f-9cc0-6d896deb2743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;wsmenucontainer&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;sectiontab aboutsec verinctn&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;courcesublst&quot;]/div[@class=&quot;lstloop&quot;]/p[1]/a[@class=&quot;dwnloadlnk&quot;]</value>
      <webElementGuid>741c6d07-01b7-4462-8714-b614484e1302</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Download')])[3]</value>
      <webElementGuid>a4b16472-b17a-4d5a-a1d1-c2485a202ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BSc. Computer Science Curriculum'])[1]/following::a[1]</value>
      <webElementGuid>32d73eb6-96d9-4895-8388-1793efc44c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Curriculum &amp; Syllabus'])[1]/following::a[1]</value>
      <webElementGuid>2dbdb2f1-8502-49e8-afe5-4628f0c44fe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[2]/preceding::a[1]</value>
      <webElementGuid>9f695107-e391-44fd-96c7-5e71a92a9586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program Educational Objectives (PEOs)'])[1]/preceding::a[2]</value>
      <webElementGuid>c9198b6e-380c-4573-8545-51bfa1a37576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download']/parent::*</value>
      <webElementGuid>d0ad345b-b155-47d0-adaa-7be71057eea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://kalasalingam.ac.in/wp-content/uploads/Curriculum/B.SC_COMPUTER%20SCIENCE_2021.pdf')]</value>
      <webElementGuid>05c84547-d92b-41a5-bbd0-de3d019de16d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/p/a</value>
      <webElementGuid>f9e8d258-2092-451d-ae91-73cd8c1df116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://kalasalingam.ac.in/wp-content/uploads/Curriculum/B.SC_COMPUTER%20SCIENCE_2021.pdf' and (text() = 'Download' or . = 'Download')]</value>
      <webElementGuid>992f433b-758a-4520-86eb-d3e4cb285835</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
