<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>130234be-82a9-45e2-93ec-62e9ac3d1dec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.owl-item.active > div.item > div.col-sm-4 > div.imgbox > div.imgshade > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(4) > .item > .col-sm-4 > .imgbox > .imgshade > img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>697506b4-3d0d-4017-b61a-1e32ef55ee89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/wp-content/uploads/2021/12/Facility-1.jpg</value>
      <webElementGuid>b5548418-ec0b-421c-95f2-80e9d6bd648d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;wsmenucontainer&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;sectiontab leadership leaderver bluedarkbg intershipwht&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;collagefac owl-carousel owl-theme owl-loaded owl-drag&quot;]/div[@class=&quot;owl-stage-outer&quot;]/div[@class=&quot;owl-stage&quot;]/div[@class=&quot;owl-item active&quot;]/div[@class=&quot;item&quot;]/div[@class=&quot;col-sm-4&quot;]/div[@class=&quot;imgbox&quot;]/div[@class=&quot;imgshade&quot;]/img[1]</value>
      <webElementGuid>4ae5d447-ec7b-4d02-ab8b-cc1be211ecb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/img</value>
      <webElementGuid>1032a949-ec88-4073-8417-99b2664484b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/wp-content/uploads/2021/12/Facility-1.jpg']</value>
      <webElementGuid>004fe75c-5ec2-4e44-9922-1b2c826356db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
